import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  page: {
    flex: 1,
  },
  pageContent: {
    paddingBottom: 90,
  },
  hero: {
    marginHorizontal: 14,
    marginTop: 14,
    borderRadius: 24,
    borderWidth: 1,
    paddingHorizontal: 18,
    paddingVertical: 20,
  },
  heroEyebrow: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.6,
  },
  heroTitle: {
    fontSize: 18,
    fontWeight: '800',
    marginTop: 0,
  },
  heroTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  heroHelpButton: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  heroHelpButtonText: {
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 18,
  },
  heroInfoBackdrop: {
    alignItems: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.4)',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  heroInfoCard: {
    borderRadius: 24,
    borderWidth: 1,
    maxWidth: 520,
    paddingHorizontal: 18,
    paddingVertical: 20,
    width: '100%',
  },
  heroInfoHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  heroInfoCloseButton: {
    alignItems: 'center',
    borderRadius: 999,
    borderWidth: 1,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  heroInfoCloseButtonText: {
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 18,
    textTransform: 'uppercase',
  },
  heroText: {
    fontSize: 14,
    lineHeight: 21,
    marginTop: 8,
  },
  summaryCard: {
    marginHorizontal: 14,
    marginTop: 14,
    borderRadius: 22,
    borderWidth: 1,
    padding: 18,
  },
  franchiseGroup: {
    marginHorizontal: 14,
    marginTop: 14,
  },
  groupedSummaryCard: {
    marginHorizontal: 0,
    marginTop: 10,
  },
  loyaltyToolbar: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    marginHorizontal: 14,
    marginTop: 16,
  },
  toolbarTitle: {
    fontSize: 18,
    fontWeight: '800',
  },
  summaryHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  summaryTitleGroup: {
    flex: 1,
    minWidth: 0,
  },
  franchiseTitle: {
    fontSize: 17,
    fontWeight: '800',
    lineHeight: 22,
  },
  franchiseTitleInsideCard: {
    marginBottom: 10,
  },
  summaryLabel: {
    fontSize: 13,
    fontWeight: '700',
  },
  summaryValue: {
    fontSize: 30,
    fontWeight: '800',
    marginTop: 8,
  },
  cardMeta: {
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
    marginTop: 2,
  },
  rewardBadge: {
    alignItems: 'center',
    borderRadius: 8,
    justifyContent: 'center',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  rewardBadgeText: {
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  stampGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 16,
    justifyContent: 'center',
    marginTop: 18,
  },
  stampSlot: {
    width: 96,
    alignItems: 'center',
    aspectRatio: 1,
    borderRadius: 16,
    borderStyle: 'dashed',
    borderWidth: 2,
    justifyContent: 'center',
    overflow: 'visible',
    padding: 8,
    position: 'relative',
  },
  stampMark: {
    alignItems: 'center',
    borderRadius: 999,
    borderStyle: 'solid',
    borderWidth: 3,
    height: 72,
    justifyContent: 'center',
    width: 72,
  },
  stampImage: {
    width: 80,
    height: 80,
    opacity: 1,
  },
  stampImageWrap: {
    alignItems: 'center',
    width: 92,
    height: 92,
    justifyContent: 'center',
    top: '50%',
    left: '50%',
    marginLeft: -46,
    marginTop: -46,
    position: 'absolute',
  },
  stampMarkMain: {
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 24,
  },
  stampMarkLabel: {
    fontSize: 8,
    fontWeight: '900',
    marginTop: 2,
    textTransform: 'uppercase',
  },
  pendingStampNumber: {
    fontSize: 28,
    fontWeight: '900',
    lineHeight: 32,
  },
  pendingStampLabel: {
    fontSize: 10,
    fontWeight: '700',
    lineHeight: 13,
    marginTop: 4,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  emptyStampBoard: {
    alignItems: 'center',
    borderRadius: 8,
    borderStyle: 'dashed',
    borderWidth: 1,
    marginTop: 18,
    padding: 14,
  },
  summaryHelp: {
    fontSize: 13,
    lineHeight: 19,
    marginTop: 12,
  },
  infoGrid: {
    paddingHorizontal: 14,
    paddingTop: 14,
    gap: 14,
  },
  infoCard: {
    borderRadius: 22,
    borderWidth: 1,
    padding: 18,
  },
  infoTitle: {
    fontSize: 16,
    fontWeight: '800',
  },
  infoMeta: {
    fontSize: 12,
    marginTop: 4,
    marginBottom: 10,
  },
  infoListItem: {
    fontSize: 14,
    lineHeight: 21,
    marginTop: 4,
  },
  infoEmpty: {
    fontSize: 13,
    lineHeight: 19,
  },
  giftTitle: {
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 8,
  },
});
